#!/usr/bin/env node
// procoder — the ratchet.
//
// Without this, opening procoder on a five-year-old repo produces four thousand
// findings and gets switched off within the hour. Existing violations are
// recorded once and suppressed everywhere; only new and changed code is gated,
// and the recorded count may shrink but never grow.
//
// Fingerprints deliberately exclude line numbers: a reformat must not resurrect
// every suppressed finding.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function normalizeLine(text) {
  return String(text || '').trim().replace(/\s+/g, ' ');
}

function fingerprint(finding, relPath, sourceLine) {
  const normalizedPath = String(relPath).replace(/\\/g, '/');
  return crypto.createHash('sha1')
    .update(`${finding.id}\0${normalizedPath}\0${normalizeLine(sourceLine)}`)
    .digest('hex');
}

function baselinePath(repoRoot, config) {
  return path.join(repoRoot, (config.baseline && config.baseline.file) || '.procoder-baseline.json');
}

function loadBaseline(repoRoot, config) {
  try {
    const parsed = JSON.parse(fs.readFileSync(baselinePath(repoRoot, config), 'utf8'));
    return new Set(Array.isArray(parsed.fingerprints) ? parsed.fingerprints : []);
  } catch (e) {
    return new Set();
  }
}

function writeBaseline(repoRoot, config, entries) {
  const payload = {
    version: 1,
    note: 'procoder ratchet. Generated by `procoder baseline`. Shrinking is good; growth fails CI.',
    fingerprints: Array.from(new Set(entries)).sort(),
  };
  fs.writeFileSync(baselinePath(repoRoot, config), JSON.stringify(payload, null, 2) + '\n');
}

function suppress(findings, { baseline, relPath, lines }) {
  if (!baseline || baseline.size === 0) return findings;
  return findings.filter((f) =>
    !baseline.has(fingerprint(f, relPath, lines[f.line - 1])));
}

function growthCheck(baseline, currentCount) {
  const delta = currentCount - baseline.size;
  return { ok: delta <= 0, delta };
}

module.exports = {
  fingerprint, loadBaseline, writeBaseline, suppress, growthCheck, baselinePath,
};
