#!/usr/bin/env node
// procoder — the ratchet.
//
// Without this, opening procoder on a five-year-old repo produces four thousand
// findings and gets switched off within the hour. Existing violations are
// recorded once and suppressed everywhere; only new and changed code is gated,
// and the recorded set may shrink but never gain a member.
//
// Fingerprints deliberately exclude line numbers: a reformat must not resurrect
// every suppressed finding.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function normalizeLine(text) {
  return String(text || '').trim().replace(/\s+/g, ' ');
}

function fingerprint(finding, relPath, sourceLine, ordinal = 0) {
  const normalizedPath = String(relPath).replace(/\\/g, '/');
  return crypto.createHash('sha1')
    .update(`${finding.id}\0${normalizedPath}\0${normalizeLine(sourceLine)}\0${ordinal}`)
    .digest('hex');
}

// One fingerprint per finding, in order. Identical violating lines share id,
// path and normalized content, so each gets the ordinal of its occurrence:
// without it one accepted violating line would accept fifty copies of itself,
// and copy-paste is exactly how legacy code grows. The ordinal is still immune
// to reformatting — indentation changes do not reorder lines.
function fingerprintsFor(findings, relPath, lines) {
  const seen = new Map();
  return findings.map((f) => {
    const sourceLine = lines[f.line - 1];
    const key = `${f.id}\0${normalizeLine(sourceLine)}`;
    const ordinal = seen.get(key) || 0;
    seen.set(key, ordinal + 1);
    return fingerprint(f, relPath, sourceLine, ordinal);
  });
}

function baselinePath(repoRoot, config) {
  return path.join(repoRoot, (config.baseline && config.baseline.file) || '.procoder-baseline.json');
}

// v2 added the occurrence ordinal to every fingerprint. v1 entries cannot be
// migrated — the ordinal was never recorded — so an old file is dropped rather
// than half-honoured. Loading it as-is would suppress nothing and report a
// legacy repo's whole backlog as new, which is how the tool gets uninstalled.
const BASELINE_VERSION = 2;

// Returns a Set, always: the hook path (checks/run.js) takes it straight to
// suppress(). A stale file yields an empty Set carrying `staleVersion`, which
// the CLI reports on stderr — the library never prints, because the hook's
// stdout is a JSON protocol and its stderr is shown to the user verbatim.
function loadBaseline(repoRoot, config) {
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(baselinePath(repoRoot, config), 'utf8'));
  } catch (e) {
    return new Set();
  }
  if (parsed.version !== BASELINE_VERSION) {
    const stale = new Set();
    stale.staleVersion = parsed.version === undefined ? 'unknown' : parsed.version;
    return stale;
  }
  return new Set(Array.isArray(parsed.fingerprints) ? parsed.fingerprints : []);
}

function writeBaseline(repoRoot, config, entries) {
  const payload = {
    version: BASELINE_VERSION,
    note: 'procoder ratchet. Generated by `procoder baseline`. Shrinking is good; growth fails CI.',
    fingerprints: Array.from(new Set(entries)).sort(),
  };
  fs.writeFileSync(baselinePath(repoRoot, config), JSON.stringify(payload, null, 2) + '\n');
}

function suppress(findings, { baseline, relPath, lines }) {
  if (!baseline || baseline.size === 0) return findings;
  const fps = fingerprintsFor(findings, relPath, lines);
  return findings.filter((f, i) => !baseline.has(fps[i]));
}

// The ratchet: a finding present today that the baseline never accepted is
// growth, no matter how many old findings were fixed in the same run.
// Counting totals instead would let a new violation ride in behind an
// unrelated fix.
function growthCheck(baseline, currentFingerprints) {
  const added = [...currentFingerprints].filter((fp) => !baseline.has(fp));
  return { ok: added.length === 0, added, delta: added.length };
}

module.exports = {
  fingerprint, fingerprintsFor, loadBaseline, writeBaseline, suppress, growthCheck, baselinePath,
  BASELINE_VERSION,
};
