package textutil

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFirstLineSkipsBlanksTrimsAndCaps(t *testing.T) {
	if got := FirstLine("\n\n  hello  \nsecond\n"); got != "hello" {
		t.Fatalf("want the first line with content, got %q", got)
	}
	if got := FirstLine("   \n\t\n"); got != "no output" {
		t.Fatalf("nothing to report must say so, got %q", got)
	}
	long := strings.Repeat("x", 300)
	if got := FirstLine(long); len(got) != maxLine {
		t.Fatalf("want a %d-char cap, got %d", maxLine, len(got))
	}
}

func TestSlugCutsAtAWordBoundary(t *testing.T) {
	if got := Slug("Hello, World!"); got != "hello-world" {
		t.Fatalf("want hello-world, got %q", got)
	}
	if got := Slug("!!!"); got != "" {
		t.Fatalf("a title with nothing usable slugs to empty, got %q", got)
	}
	long := Slug(strings.Repeat("very long words about acceptance ", 8))
	if len(long) > maxSlug {
		t.Fatalf("slug must be capped at %d, got %d: %q", maxSlug, len(long), long)
	}
	if strings.HasSuffix(long, "-") || !strings.HasPrefix(long, "very-long") {
		t.Fatalf("the cut must land on a word boundary and keep the head: %q", long)
	}
}

func TestSectionStopsAtTheNextHeading(t *testing.T) {
	doc := "# T\n\n## One\n\nfirst body\n\n## Two\n\nsecond body\n"
	if got := strings.TrimSpace(Section(doc, "One")); got != "first body" {
		t.Fatalf("want the first section only, got %q", got)
	}
	if got := Section(doc, "Missing"); got != "" {
		t.Fatalf("an absent section is empty, got %q", got)
	}
}

func TestStripCommentsRemovesGuidanceIncludingUnterminated(t *testing.T) {
	if got := strings.TrimSpace(StripComments("a <!-- hint --> b")); got != "a  b" {
		t.Fatalf("want the comment gone, got %q", got)
	}
	if got := StripComments("kept <!-- never closed"); got != "kept " {
		t.Fatalf("an unterminated comment truncates rather than returning everything: %q", got)
	}
}

// A dropped character is a boundary, never glue. Welding the halves of a
// word together made a story about `answers.md` unfindable by anyone
// grepping for "answers", and collapsed v1.2.3 and v12.3 onto one slug —
// which surfaces as `backlog story` refusing on a collision the user cannot
// see the cause of.
// proved by: dropped the default branch back to the old three-character
// whitelist — "answers.md" then slugs to "answersmd" and the two versions
// below collide.
func TestPunctuationSeparatesInsteadOfWelding(t *testing.T) {
	for title, want := range map[string]string{
		"a spec question ANSWERED in `answers.md` no longer blocks": "a-spec-question-answered-in-answers-md-no-longer-blocks",
		"read config.toml and package.json":                         "read-config-toml-and-package-json",
		"the v1.2.3 tag is read":                                    "the-v1-2-3-tag-is-read",
	} {
		if got := Slug(title); got != want {
			t.Errorf("Slug(%q)\n got %q\nwant %q", title, got, want)
		}
	}
	if Slug("v1.2.3") == Slug("v12.3") {
		t.Errorf("two different versions must not slug alike: %q", Slug("v1.2.3"))
	}
	// Heavy punctuation must not become a slug of mostly dashes, and must
	// not lead or trail with one — those are file names.
	got := Slug("`.procoder/ask/QA.md` and `.procoder/ask/answers.md` are written")
	if strings.Contains(got, "--") || strings.HasPrefix(got, "-") || strings.HasSuffix(got, "-") {
		t.Errorf("runs of dashes must collapse and the ends must be clean: %q", got)
	}
}

// The ids already on disk were generated by the old rule, and `Sprint:`
// fields, closed-story evidence and commit messages all reference them. This
// is a change to how NEW names are made; a rename pass would break every one
// of those references, so the existing files must still be exactly where
// they are.
// proved by: made Slug rewrite existing names by running it over each file's
// own id — every story seeded before this change then fails to resolve.
func TestExistingIdsOnDiskStillResolve(t *testing.T) {
	dir := filepath.Join("..", "..", ".procoder", "backlog", "stories")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Skip("no seeded stories to check: ", err)
	}
	checked := 0
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		checked++
		if _, err := os.Stat(filepath.Join(dir, e.Name())); err != nil {
			t.Errorf("%s no longer resolves: %v", e.Name(), err)
		}
	}
	if checked == 0 {
		t.Error("no story files were checked — this guard proves nothing")
	}
}

// A Latin letter with a mark is that letter, for a file name's purposes.
// Dropping the rune left "caf" — a word that is neither the title nor
// findable by it — and someone typing "cafe" would not match either.
// proved by: removed the latin1 case from Slug — "café" then slugs to
// "caf" and "straße" to "stra-e", and neither is findable by the word it
// was made from.
func TestAccentedLettersFoldRatherThanVanish(t *testing.T) {
	for title, want := range map[string]string{
		"café-story.md is quoted": "cafe-story-md-is-quoted",
		"naïve façade":            "naive-facade",
		"Müller straße":           "muller-strasse",
		"ÉCOLE normale":           "ecole-normale", // uppercase folds too
		"Łódź report":             "lodz-report",
	} {
		if got := Slug(title); got != want {
			t.Errorf("Slug(%q)\n got %q\nwant %q", title, got, want)
		}
	}
	// The table is Latin only, and says so. A script it does not cover
	// still loses its letters — the documented ceiling, asserted so that a
	// later table covering more scripts fails here and gets read.
	if got := Slug("日本語 title"); got != "title" {
		t.Errorf("non-Latin scripts are the known ceiling: %q", got)
	}
}
